title: Yifan Liu
logo: /assets/img/profile.jpg
description: MPhil in Fudan University, Computer Vision & AI | 3D Reconstruction | Neural Rendering | Model Optimization.
theme: jekyll-theme-minimal
github_username: yifan-liu0715

sass:
  sass_dir: _sass