title: Yifan Liu
logo: /assets/img/logo.png
description: MPhil in Fudan University, Computer Vision & AI | 3D Reconstruction | Neural Rendering | Model Optimization.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
github_username: yifan-liu0715
